language: cpp
compiler:
    - gcc
    - clang
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
    irc:
        channels:
            - "chat.freenode.net#glsl-debugger"
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
    - linux
