language: cpp
compiler:
    - gcc
    - clang
before_install:
     "yes" | sudo add-apt-repository ppa:kalakris/cmake
    - sudo apt-get update -qq
    - sudo apt-get install cmake
install:
    - sudo apt-get install qt4-dev-tools libqt4-opengl-dev
before_script:
    - mkdir build
    - cd build
    - cmake ..
script: make
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
    irc:
        channels:
            - "chat.freenode.net#glsl-debugger"
        template:
            - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
os:
    - linux
